### ISSUE TITLE
init-db-user.sh misses execution permissions

### ISSUE THREAD

**Issue by ngraf** [pixeleye-io/pixeleye#318]
**Describe the bug**
I followed the guide for self-hosting at https://pixeleye.io/docs/guides/self-hosting and failed.

**To Reproduce**
1. Check out [pixel](https://github.com/pixeleye-io/pixeleye) repository
2. Enter "docker" directory of checked out repository.
3. Create copy of `config/template.kratos.yml` at `config/kratos.yml` (**It would be nice if this step gets documented! It took me some time to figure this out.**)
4. Run `docker compose -f docker-compose-self-hosting.yml up`
5. See error in stdout:
`postgres-1           | /usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/init-user-db.sh: /bin/bash: bad interpreter: Permission denied`

**Expected behavior**
Self-hosting works following the guide.

**Screenshots**
![image](https://github.com/pixeleye-io/pixeleye/assets/7094389/8bc24457-e1b7-436d-b44b-c16d653fe0bc)

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
- As "docker" client I use "Docker for Desktop" for MacOS.

----

**Possible fix**
- This is how I fixed it: Add execution permissions to `init-user-db.sh` file and commit them. I added them and then the script worked for me. Command to add execution permission I did was `chmod +x init-user-db.sh`. Feel free to do the same and merge it.

**Comment by AlfieJones** [comment]
Thanks for sharing this issue!

I've not been able to reproduce locally with windows or wsl but I've put together a potential fix which should hopefully do the trick 🤞.

Could you test the new docker-compose file? 

You can find the file here: https://github.com/pixeleye-io/pixeleye/blob/3879dc05f025eefde3d6ed28e014e45679a72a6c/docker/docker-compose-dev.yml 
You also need the new dockerFile to be place inside the ./config folder (https://github.com/pixeleye-io/pixeleye/blob/3879dc05f025eefde3d6ed28e014e45679a72a6c/docker/config/Dockerfile.psql)

I've also added a note to the docs to make it clearer that we need the config folder in addition to the compose file.

**Comment by ngraf** [comment]
What you provided did not solve the issue for me.
Only after I executed `chmod +x init-user-db.sh`, the setup began to work for me.

**Comment by AlfieJones** [comment]
I forgot to remove the old config 🤦. If you could check this new dockerfile https://github.com/pixeleye-io/pixeleye/blob/fix-self-hosting-permissions/docker/docker-compose-dev.yml that'd be awesome!

**Comment by ngraf** [comment]
@AlfieJones , alright. Using  https://github.com/pixeleye-io/pixeleye/blob/fix-self-hosting-permissions/docker/docker-compose-dev.yml enables me to run `docker compose -f docker-compose-dev.yml up` succesfully with database initiated.
Feel free to patch your project with that yml.

**Comment by AlfieJones** [comment]
Thanks for your help 👍
