### ISSUE TITLE
Every second Cypress run fails because port 3003 is not closed properly

### ISSUE THREAD

**Issue by ngraf** [pixeleye-io/pixeleye#332]
**Describe the bug**
Every second test run with Cypress and Pixeleye active fails. The reason is that the pixeleye does not close port 3003 properly.

**To Reproduce**
1. Clone "pixeleye" repository.
2. Go to folder `examples/cypress`
3. Install dependencies `pnpm install`
4. Run cypress tests with pixeleye active `pixeleye exec -- cypress run` -> 🟢 success
5. Run cypress tests with pixeleye active again `pixeleye exec -- cypress run` -> 🔴 fail because port 3003 is occupied
6. Run cypress tests with pixeleye active again `pixeleye exec -- cypress run` -> 🟢 success
7. Run cypress tests with pixeleye active again `pixeleye exec -- cypress run` -> 🔴 fail because port 3003 is occupied
8. Run cypress tests with pixeleye active again `pixeleye exec -- cypress run` -> 🟢 success
9. Run cypress tests with pixeleye active again `pixeleye exec -- cypress run` -> 🔴 fail because port 3003 is occupied
...

**Expected behavior**
Port 3003 is properly closed, so that every preceding test run will not fail because port is already occupied.

**Screenshots**
1) Start of test:
![image](https://github.com/pixeleye-io/pixeleye/assets/7094389/90b1b8ff-2a67-4dca-833b-0876318d71c5)
2) Failing Cypress test:
![image](https://github.com/pixeleye-io/pixeleye/assets/7094389/40cd07d6-2946-42b3-b8e3-037c4c8af3bf)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: not sure

**Versions**
- Cypress: 13.10.0
- PIxeleye: 0.8.7

**Additional context**
- The problem occurs no matter if I configure SaaS Pixeleye.io as endpoint or a locally hosted Pixel eye server.
- If I do this as a workaround I get 100% success rate:
`kill-port 3003; npm run cypress:run; kill-port 3003; npm run cypress:run;kill-port 3003; npm run cypress:run; kill-port 3003; npm run cypress:run;kill-port 3003;`

**Comment by AlfieJones** [comment]
I've not been able to replicate this but have updated our cleanup function to more aggressivley kill the child processes.

Could you verify if pixeleye@0.8.8 fixes your issue?

**Comment by ngraf** [comment]
pixeleye@0.8.8 stablized it ✅

I close this issue now with status fixed. 
That was a blocker for me using this tool. Now not anymore.
Thanks a lot.
