### ISSUE TITLE
Doc links are broken (Server error)

### ISSUE THREAD

**Issue by CodeShakingSheep** [pixeleye-io/pixeleye#338]
**Describe the bug**
When I click on https://pixeleye.io/docs/getting-started/introduction there is a server error and the docs are not loaded.

**To Reproduce**
Click on this link: https://pixeleye.io/docs/getting-started/introduction

**Expected behavior**
Docs should load fine.

**Screenshots**
![image](https://github.com/user-attachments/assets/e4657e4a-c681-45c4-9525-777eaf82ed42)

**Comment by AlfieJones** [comment]
Thanks for reporting this, it's now fixed
