### ISSUE TITLE
Hosted version times out

### ISSUE THREAD

**Issue by michaelhthomas** [pixeleye-io/pixeleye#339]
https://pixeleye.io/dashboard

![image](https://github.com/user-attachments/assets/89cce776-3040-4c29-babe-811522976a69)

**Comment by georgiablanco** [comment]
I have also seen this this morning when attempting to create an account:
![image](https://github.com/user-attachments/assets/7cbc863c-02d3-4765-adc6-818ad47774fc)

**Comment by AlfieJones** [comment]
It should be up and running again
